import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { wrapper } from "./redux/store";
import { Provider } from "react-redux";
import { AppProps } from "next/app";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

function App({ Component, pageProps }: AppProps) {
  const { store, props } = wrapper.useWrappedStore(pageProps);

  return (
    <Provider store={store}>
      <RootLayout>{props.children}</RootLayout>
    </Provider>
  );
}

export default wrapper.withRedux(App);
